version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Charger les variables depuis .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    env_file:
      - .env  # Charger les variables pour la base de données
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: